name: Run Full Regression Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug environment variables
        run:
          echo "Email: ${{ secrets.MSALAMON_LOGIN_EMAIL_ADDRESS }}"
          echo "Password: ${{ secrets.MSALAMON_LOGIN_EMAIL_PASSWORD }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          java-package: jdk
          architecture: x64
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run full regression tests
        env:
          MSALAMON_LOGIN_EMAIL_ADDRESS: ${{ secrets.MSALAMON_LOGIN_EMAIL_ADDRESS }}
          MSALAMON_LOGIN_EMAIL_PASSWORD: ${{ secrets.MSALAMON_LOGIN_EMAIL_PASSWORD }}
        run: mvn test

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Upload Allure Report to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin
