name: CI Workflow

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Warunek uruchomienia tylko przy PR

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run smoke tests
        run: mvn test -Dtest=SmokeTest

  regression-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Uruchomienie tylko przy push do mastera

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run full regression tests
        run: mvn test
